version: '3.8'

services:
  spring-app:
    build: 
      context: portfolio_back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      API_TOKEN: ${API_TOKEN}
      SPRING_MAIL_USERNAME: ${SMTP_EMAIL}
      SPRING_MAIL_PASSWORD: ${SMTP_PASSWORD}
    networks:
      - conexion_from_spring
    restart: always

  mysql-db:
    build: 
      context: ./MySQL
      dockerfile: Dockerfile
    container_name: database
    restart: always
    ports:
      - 3307:3306
    volumes:
      - ./MySQL/volumes:/var/lib/mysql
    hostname: mysql-db
    networks:
      - conexion_from_spring
    healthcheck:
        test: ["CMD","mysql", "-u", "root", "-proot"]
        interval: 30s
        timeout: 10s
        retries: 5

  adminer:
    image: adminer
    container_name: adminer_spring
    restart: always
    ports:
      - "8080:8080"
    networks:
      - conexion_from_spring

networks:
  conexion_from_spring:
    driver: bridge

volumes:
  mysql-data:
    driver: local